### PR TITLE
Add support for protected content for people who are attendees of other tickets

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Update the protected content shortcode so it can handle NOT checks (attendee, but NOT of certain tickets).

Also updates formatting of some of the extension code.

### CODE REVIEW

**Review by juanfra — COMMENTED** [review]
Looking great! I think the only thing missing would be adding changelog entries, as these changes should be released in a new version.

**Comment by sc0ttkclark** [comment]
@juanfra Changelog in readme.txt? What is release date? Do we have initial tag/release in GitHub already?

**Comment by juanfra** [comment]
@sc0ttkclark Yes. I haven't been involved in extensions until now so I'm not sure about the "release process", but I can see that they're versioned here: https://theeventscalendar.com/extensions/ - So I feel we could start doing that, and applying the same procedure as the plugins maybe? (In terms of branching and readme)

**Comment by sc0ttkclark** [comment]
Updated changelog

**Review by juanfra — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
